/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as EvaluationsRouteImport } from './routes/evaluations'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ExceptionsExceptionIdRouteImport } from './routes/exceptions.$exceptionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRoute = EvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsExceptionIdRoute = ExceptionsExceptionIdRouteImport.update({
  id: '/$exceptionId',
  path: '/$exceptionId',
  getParentRoute: () => ExceptionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/evaluations': typeof EvaluationsRoute
  '/exceptions': typeof ExceptionsRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/exceptions/$exceptionId': typeof ExceptionsExceptionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/evaluations': typeof EvaluationsRoute
  '/exceptions': typeof ExceptionsRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/exceptions/$exceptionId': typeof ExceptionsExceptionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/evaluations': typeof EvaluationsRoute
  '/exceptions': typeof ExceptionsRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/exceptions/$exceptionId': typeof ExceptionsExceptionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audit'
    | '/evaluations'
    | '/exceptions'
    | '/knowledge'
    | '/observability'
    | '/settings'
    | '/exceptions/$exceptionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit'
    | '/evaluations'
    | '/exceptions'
    | '/knowledge'
    | '/observability'
    | '/settings'
    | '/exceptions/$exceptionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/audit'
    | '/evaluations'
    | '/exceptions'
    | '/knowledge'
    | '/observability'
    | '/settings'
    | '/exceptions/$exceptionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuditRoute: typeof AuditRoute
  EvaluationsRoute: typeof EvaluationsRoute
  ExceptionsRoute: typeof ExceptionsRouteWithChildren
  KnowledgeRoute: typeof KnowledgeRoute
  ObservabilityRoute: typeof ObservabilityRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations': {
      id: '/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof EvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions/$exceptionId': {
      id: '/exceptions/$exceptionId'
      path: '/$exceptionId'
      fullPath: '/exceptions/$exceptionId'
      preLoaderRoute: typeof ExceptionsExceptionIdRouteImport
      parentRoute: typeof ExceptionsRoute
    }
  }
}

interface ExceptionsRouteChildren {
  ExceptionsExceptionIdRoute: typeof ExceptionsExceptionIdRoute
}

const ExceptionsRouteChildren: ExceptionsRouteChildren = {
  ExceptionsExceptionIdRoute: ExceptionsExceptionIdRoute,
}

const ExceptionsRouteWithChildren = ExceptionsRoute._addFileChildren(
  ExceptionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuditRoute: AuditRoute,
  EvaluationsRoute: EvaluationsRoute,
  ExceptionsRoute: ExceptionsRouteWithChildren,
  KnowledgeRoute: KnowledgeRoute,
  ObservabilityRoute: ObservabilityRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
